# Generated by Django 3.2 on 2023-10-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guitars',
            new_name='Guitar',
        ),
    ]
