# Generated by Django 3.2 on 2023-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_guitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
